export const productsScargo = [
  {
    id: 1,
    title: "Wide Leg",
    description: "Pantalon jean de beba Wide Leg, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 21,
      3: 22,
      4: 23,
      5: 24,
      6: 25,
    },

    category: "bebes",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/6/2.jpg",
      "https://i.dummyjson.com/data/products/6/3.png",
      "https://i.dummyjson.com/data/products/6/4.jpg",
    ],
  },
  {
    id: 2,
    title: "Campera azul",
    description: "Campera jean azul de niños elastizada, talles 4-16 ",
    price: 899,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 17.94,
    rating: 4.44,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "niños",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: [
      "/productos/2.jpeg",
      "https://i.dummyjson.com/data/products/2/2.jpg",
      "https://i.dummyjson.com/data/products/2/3.jpg",
      "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    ],
  },
  {
    id: 3,
    title: "Cargo niña",
    description:
      "Cargo jean oscuro con puño elastizado de niñas, talles 4 al 16",
    price: 1249,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 15.46,
    rating: 4.09,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "niñas",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: ["/productos/3.jpeg"],
  },
  {
    id: 4,
    title: "Cargo niña",
    description:
      "Cargo jean claro con puño elastizado para niñas talles 4 al 16",
    price: 280,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 17.91,
    rating: 4.3,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "niñas",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: [
      "/productos/4.jpeg",
      "https://i.dummyjson.com/data/products/4/2.jpg",
      "https://i.dummyjson.com/data/products/4/3.jpg",
      "https://i.dummyjson.com/data/products/4/4.jpg",
      "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    ],
  },
  {
    id: 5,
    title: "Cargo niño",
    description:
      "Cargo gabardina beige con puño elastizado para niños talles 4 al 16",
    price: 499,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 10.58,
    rating: 4.09,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "niños",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: [
      "/productos/5.jpeg",
      "https://i.dummyjson.com/data/products/5/2.jpg",
      "https://i.dummyjson.com/data/products/5/3.jpg",
    ],
  },
  {
    id: 6,
    title: "Cargo niños",
    description:
      "Cargo jean negro con puño elastizado para niños, talles 4 al 16",
    price: 1499,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 4.15,
    rating: 4.25,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "niños",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: [
      "/productos/6.jpeg",
      "https://i.dummyjson.com/data/products/7/2.jpg",
      "https://i.dummyjson.com/data/products/7/3.jpg",
      "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    ],
  },
  {
    id: 7,
    title: "Cargo niñas",
    description:
      "Cargo jean negro con puño elastizado para niñas talles 4 al 16",
    price: 549,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 12.96,
    rating: 4.69,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "niñas",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "/productos/7.jpeg",
      "https://i.dummyjson.com/data/products/1/2.jpg",
      "https://i.dummyjson.com/data/products/1/3.jpg",
      "https://i.dummyjson.com/data/products/1/4.jpg",
      "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    ],
  },
  {
    id: 8,
    title: "Mom bebe",
    description: "Mom jean claro con puño elastizado para bebes talles 1 al 6.",
    price: 1499,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 10.23,
    rating: 4.43,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: [
      "/productos/8.jpeg",
      "https://i.dummyjson.com/data/products/8/2.jpg",
      "https://i.dummyjson.com/data/products/8/3.jpg",
      "https://i.dummyjson.com/data/products/8/4.jpg",
      "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    ],
  },
  {
    id: 9,
    title: "Mom bebe",
    description:
      "Mom jean oscurto con puño elastizado para bebes talles 1 al 6.",
    price: 1499,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 10.23,
    rating: 4.43,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: [
      "/productos/9.jpeg",
      "https://i.dummyjson.com/data/products/9/2.png",
      "https://i.dummyjson.com/data/products/9/3.png",
      "https://i.dummyjson.com/data/products/9/4.jpg",
      "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    ],
  },
  {
    id: 10,
    title: "Mom bebe",
    description: "Mom jean con puño elastizado para bebes talles 1 al 6.",
    price: 1499,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 10.23,
    rating: 4.43,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: [
      "/productos/10.jpeg",
      "https://i.dummyjson.com/data/products/10/2.jpg",
      "https://i.dummyjson.com/data/products/10/3.jpg",
      "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    ],
  },
  {
    id: 11,
    title: "Wide leg baby",
    description: "Wide leg gabardina salmon para bebas talles 1 al 6.",
    price: 13,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 8.4,
    rating: 4.26,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    images: [
      "/productos/11.jpeg",
      "https://i.dummyjson.com/data/products/11/2.jpg",
      "https://i.dummyjson.com/data/products/11/3.jpg",
      "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    ],
  },
  {
    id: 12,
    title: "Cargo niños",
    description:
      "Cargo jean con roturas con puño elastizado para niños, talles 4 al 16",
    price: 549,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["azul", "negro", "gris", "rosa"],
    discountPercentage: 12.96,
    rating: 4.69,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "niños",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "/productos/12.jpeg",
      "https://i.dummyjson.com/data/products/12/2.jpg",
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/4.jpg",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
  },
  {
    id: 13,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/13/2.png",
      "https://i.dummyjson.com/data/products/13/3.jpg",
      "https://i.dummyjson.com/data/products/13/4.jpg",
      "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    ],
  },
  {
    id: 14,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/14/2.jpg",
      "https://i.dummyjson.com/data/products/14/3.jpg",
      "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    ],
  },
  {
    id: 15,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/15/2.jpg",
      "https://i.dummyjson.com/data/products/15/3.jpg",
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
  },
  {
    id: 16,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/16/2.webp",
      "https://i.dummyjson.com/data/products/16/3.jpg",
      "https://i.dummyjson.com/data/products/16/4.jpg",
      "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    ],
  },
  {
    id: 17,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/17/2.jpg",
      "https://i.dummyjson.com/data/products/17/3.jpg",
      "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    ],
  },
  {
    id: 18,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/18/2.jpg",
      "https://i.dummyjson.com/data/products/18/3.jpg",
      "https://i.dummyjson.com/data/products/18/4.jpg",
      "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    ],
  },
  {
    id: 19,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/19/2.jpg",
      "https://i.dummyjson.com/data/products/19/3.png",
      "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    ],
  },
  {
    id: 20,
    title: "Wide Leg baby",
    description: "Pantalon wide leg jean negro de beba, Talles 1 al 6",
    price: 1749,
    talles: [1, 2, 3, 4, 5, 6],
    colores: ["blue", "black", "grey", "pink"],
    discountPercentage: 11.02,
    rating: 4.57,
    stock: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
    },

    category: "bebes",
    images: [
      "/productos/1.jpeg",
      "https://i.dummyjson.com/data/products/20/2.jpg",
      "https://i.dummyjson.com/data/products/20/3.jpg",
      "https://i.dummyjson.com/data/products/20/4.jpg",
      "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    ],
  },
];
